spring.application.name=TaskManagementSystem

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d88m666q1p3s73f2m730-a.singapore-postgres.render.com:5432/ecommerce_ct8l
spring.datasource.username=ecommerce_ct8l_user
spring.datasource.password=2BJ82N4nxNFh0kw3cvKm7wEr0eTitPup
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT}







#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/TaskManage
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
